//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLLB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public int ImportId { get; set; }
        public int BarNumber { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public bool FreeConsultation { get; set; }
        public bool CreditCard { get; set; }
        public string Email { get; set; }
        public string OfficePhoneNumber { get; set; }
        public string CellPhone { get; set; }
        public string Fax { get; set; }
        public string WebSite { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string GooglePlus { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Admitted { get; set; }
        public int Status { get; set; }
        public string Code { get; set; }
        public Nullable<long> LawSchoolId { get; set; }
        public Nullable<int> GraduatedYear { get; set; }
        public string Firm { get; set; }
        public Nullable<long> FirmPositionId { get; set; }
        public long PlanId { get; set; }
        public string FullName { get; set; }
    }
}
