//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLLB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortenURL
    {
        public int ID { get; set; }
        public string ShortenURL1 { get; set; }
        public string URL { get; set; }
        public Nullable<int> MessageID { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
