//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLLB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unsubscription
    {
        public int UnsubcriptionID { get; set; }
        public Nullable<int> ProID { get; set; }
        public Nullable<System.DateTime> UnsubscribeOn { get; set; }
        public Nullable<int> UnsubcriptionReason { get; set; }
        public string Email { get; set; }
    
        public virtual UnsubscribeReason UnsubscribeReason { get; set; }
    }
}
